name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
pull_requests: 
branches:
- main
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Select XCode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Set up Ruby 
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: 3.0.2

      - name: Install fastlane
        run: gem install fastlane

      - name: Run tests
        run: cd CurrencyQuotationApp/; fastlane tests
      
